apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: construction
type: Opaque
data:
  POSTGRES_USER: ZGV2dXNlcg==        # base64 of "devuser"
  POSTGRES_PASSWORD: ZGV2cGFzcw==    # base64 of "devpass"
  POSTGRES_DB: Y29uc3RydWN0aW9uZGI=  # base64 of "constructiondb"