apiVersion: v1
kind: Secret
metadata:
  name: construction-secret
  namespace: construction
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RldnVzZXI6ZGV2cGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY29uc3RydWN0aW9uZGI=
